using System;
using System.Collections.Generic;
using Godot;

namespace AnimalCrossing.Disc;

/// <summary>
/// Loads game assets from the disc image DOL and REL modules.
/// Equivalent to pc_assets.c in the original port.
///
/// Assets are stored at fixed offsets within the main.dol executable and the
/// foresta.rel module. The asset table maps each asset to its source (DOL/REL),
/// byte offset, size, and byte-swap type needed for big-endian → little-endian conversion.
/// </summary>
public class AssetLoader
{
    private readonly DiscReader _disc;
    private readonly Dictionary<string, Asset> _assets = new();

    public int AssetCount => _assets.Count;

    public enum AssetSource
    {
        DOL,    // From main.dol executable
        REL,    // From foresta.rel module
        File,   // From standalone file
    }

    public enum SwapType
    {
        None,   // No byte swapping needed
        U16,    // Swap every 2 bytes
        U32,    // Swap every 4 bytes
        Vtx,    // Vertex data: swap first 12 bytes as u16 pairs, rest as u16
    }

    public struct Asset
    {
        public string Name;
        public AssetSource Source;
        public uint Offset;
        public uint Size;
        public SwapType Swap;
        public byte[]? Data;
    }

    public AssetLoader(DiscReader disc)
    {
        _disc = disc;
    }

    /// <summary>Load all assets from DOL and REL data.</summary>
    public void LoadAll()
    {
        if (_disc.DolData == null)
        {
            GD.PrintErr("[ASSETS] No DOL data available");
            return;
        }

        GD.Print("[ASSETS] Loading assets from disc image...");

        // In the original port, pc_assets.c is auto-generated by gen_runtime_assets.py
        // with ~2500 asset entries. Here we provide the loading infrastructure.
        // Assets will be populated from the asset table as it's ported.

        GD.Print($"[ASSETS] Loaded {_assets.Count} assets");
    }

    /// <summary>Load a single asset by name.</summary>
    public byte[]? LoadAsset(string name)
    {
        if (_assets.TryGetValue(name, out var asset))
        {
            if (asset.Data != null)
                return asset.Data;

            // Load from source
            asset.Data = LoadFromSource(asset);
            _assets[name] = asset;
            return asset.Data;
        }

        return null;
    }

    /// <summary>Register an asset in the table (called during initialization).</summary>
    public void RegisterAsset(string name, AssetSource source, uint offset, uint size, SwapType swap = SwapType.None)
    {
        _assets[name] = new Asset
        {
            Name = name,
            Source = source,
            Offset = offset,
            Size = size,
            Swap = swap,
        };
    }

    /// <summary>Get raw bytes from DOL at a specific offset.</summary>
    public byte[]? ReadDOL(uint offset, uint size)
    {
        if (_disc.DolData == null || offset + size > _disc.DolData.Length)
            return null;

        byte[] data = new byte[size];
        Array.Copy(_disc.DolData, offset, data, 0, size);
        return data;
    }

    /// <summary>Get raw bytes from REL at a specific offset.</summary>
    public byte[]? ReadREL(uint offset, uint size)
    {
        if (_disc.RelData == null || offset + size > _disc.RelData.Length)
            return null;

        byte[] data = new byte[size];
        Array.Copy(_disc.RelData, offset, data, 0, size);
        return data;
    }

    private byte[]? LoadFromSource(Asset asset)
    {
        byte[]? source = asset.Source switch
        {
            AssetSource.DOL => _disc.DolData,
            AssetSource.REL => _disc.RelData,
            _ => null,
        };

        if (source == null || asset.Offset + asset.Size > source.Length)
            return null;

        byte[] data = new byte[asset.Size];
        Array.Copy(source, asset.Offset, data, 0, asset.Size);

        // Apply byte swapping for big-endian → little-endian
        ByteSwap(data, asset.Swap);
        return data;
    }

    /// <summary>Convert big-endian data to little-endian based on swap type.</summary>
    public static void ByteSwap(byte[] data, SwapType swap)
    {
        switch (swap)
        {
            case SwapType.U16:
                SwapU16(data);
                break;
            case SwapType.U32:
                SwapU32(data);
                break;
            case SwapType.Vtx:
                SwapVertex(data);
                break;
            case SwapType.None:
            default:
                break;
        }
    }

    private static void SwapU16(byte[] data)
    {
        for (int i = 0; i + 1 < data.Length; i += 2)
        {
            (data[i], data[i + 1]) = (data[i + 1], data[i]);
        }
    }

    private static void SwapU32(byte[] data)
    {
        for (int i = 0; i + 3 < data.Length; i += 4)
        {
            (data[i], data[i + 3]) = (data[i + 3], data[i]);
            (data[i + 1], data[i + 2]) = (data[i + 2], data[i + 1]);
        }
    }

    private static void SwapVertex(byte[] data)
    {
        // Vertex format: first 12 bytes are position (6 x s16), rest are u16
        // Swap all as u16 pairs
        SwapU16(data);
    }
}
